// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: docs.ipynb

import path from "node:path";
import type { Config } from "jurassic/config.ts";
import { getExportedDefinitions } from "jurassic/utils.ts";
import {
  getCellOutput,
  getNbTitle,
  getNotebooksToProcess,
  loadNb,
} from "jurassic/notebooks.ts";
import type { Cell, Nb } from "jurassic/notebooks.ts";
export const isDocCell = (cell: Cell): boolean =>
  cell.cell_type === "markdown" ||
  (cell.cell_type === "code" &&
    cell.source.length > 0 &&
    !cell.source[0].match(/^\/\/\S*|\S*export/gi));
const wrapCode = (code: string): string => "```typescript\n" + code + "\n```\n";

export const processCell = (cell: Cell): string => {
  if (cell.cell_type === "markdown") {
    // markdown cells - just show content directly
    return cell.source.join("");
  }

  if (cell.cell_type === "code") {
    // code cells - show code and output
    const code = cell.source.join("");
    const exports = getExportedDefinitions(code);

    if (!exports) {
      return (
        wrapCode(code) +
        "\n" +
        getCellOutput(cell)
      );
    }

    return exports.reduce(
      (acc, e) => acc + "\n" + `## ${e.name}` + "\n\n" + wrapCode(e.signature),
      "",
    );
  }

  return "";
};
const moduleHeader = (): string => `
---
outline: deep
---
`;

const processNb = async (
  nbPath: string,
  moduleName: string,
): Promise<[Nb, string]> => {
  // TODO: make use of moduleName
  console.log("Processing notebook", moduleName);
  const nb = await loadNb(nbPath);
  return [
    nb,
    nb.cells.reduce(
      (acc, cell) => acc + "\n\n" + processCell(cell),
      moduleHeader(),
    ).trim(),
  ];
};
const indexMd = `
---
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "Jurassic"
  text: "Jurassic docs"
  tagline: My great project tagline
  actions:
    - theme: brand
      text: Markdown Examples
      link: /markdown-examples
    - theme: alt
      text: API Examples
      link: /api-examples

features:
  - title: Feature A
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
  - title: Feature B
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
  - title: Feature C
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
---
`.trim();
const packageJSON = `
{
  "name": "docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vitepress dev --open",
    "docs:build": "vitepress build",
    "docs:preview": "vitepress preview"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "vitepress": "^1.5.0"
  }
}`.trim();
const vitePressConfig = (notebooks: Nb[], mds: string[]): string => {
  const docs = `{
        text: "Docs",
        items: ${
    JSON.stringify(
      // sort by notebook name length for now
      [...notebooks].map((nb, i) => ({
        text: getNbTitle(nb),
        link: `/${mds[i].replace(".md", "")}`,
      })),
    )
  },
      },`;
  return `
import { defineConfig } from "vitepress";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "Jurassic",
  description: "Jurassic docs",
  base: "/jurassic/",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: "Home", link: "/" },
    ],

    search: {
      provider: "local",
    },

    sidebar: [${docs}],

    socialLinks: [
      { icon: "github", link: "https://github.com/vuejs/vitepress" },
    ],
  },
});
`.trim();
};
const gitIgnore = `
node_modules
.vitepress/dist
.vitepress/cache
`.trim();
export const generateDocs = async (
  notebookPath: string,
  config: Config,
): Promise<void> => {
  const notebooksToProcess: string[] = await getNotebooksToProcess(
    notebookPath,
    config,
  );
  const notebooks: Nb[] = [];
  const mds: string[] = [];

  try {
    await Deno.stat(config.docsPath);
    await Deno.remove(config.docsPath, { recursive: true });
  } catch {
    // noop
  }

  // let's go through all notebooks and process them one by one
  for (const notebook of notebooksToProcess) {
    // output module is the same as the input notebook, but with .ts extension
    const outputFile = notebook.replace(".ipynb", ".md");
    mds.push(outputFile);
    // make sure we preserve subdirectories if any
    const outputDir = path.join(config.docsPath, path.dirname(outputFile));
    await Deno.mkdir(outputDir, { recursive: true });

    const [nb, md] = await processNb(
      path.resolve(config.nbsPath, notebook),
      notebook,
    );
    notebooks.push(nb);
    await Deno.writeTextFile(path.join(config.docsPath, outputFile), md);
  }

  const filesToWrite = {
    "index.md": indexMd,
    "package.json": packageJSON,
    ".vitepress/config.mts": vitePressConfig(notebooks, mds),
    ".gitignore": gitIgnore,
  };

  // create .vitepress directory
  await Deno.mkdir(path.join(config.docsPath, ".vitepress"));

  // Write all files in a loop
  for (const [filename, content] of Object.entries(filesToWrite)) {
    await Deno.writeTextFile(path.join(config.docsPath, filename), content);
  }
};
