name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish
    docs:
      needs: publish
      uses: callmephilip/jurassic/.github/workflows/docs.yml@main
