name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: callmephilip/jurassic/.github/workflows/build.yml@main
      - name: Publish package
        run: npx jsr publish
