name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install jupyter notebook
        run: |
          pip install notebook

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install jupyter deno kernel
        run: deno jupyter --unstable --install

      - name: Run export
        run: deno task build

      - name: Check on git
        run: git diff

      - name: Tests
        run: deno test --allow-all

      - name: Publish package
        run: npx jsr publish
