name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish
